### PR TITLE
Fix ekcert checking

### LINKED ISSUE #19: could not verify cert: x509: unhandled critical extension
Someone reported an issue on Slack about getting this error from the plugin. After some investigate it seems to be because the EK certificate has the Subject Alternative Names extensions marked as critical while using DirName SANs. Since Go doesn't understand DirNames (or at least I think that's the issue, didn't get to try with other types of SANs) it marks these as unhandled.

I could get it to work with the following change:
```
--- a/pkg/common/tpm_attestor.go
+++ b/pkg/common/tpm_attestor.go
@@ -20,6 +20,7 @@ import (
        "bytes"
        "crypto/sha256"
        "crypto/x509"
+       "encoding/asn1"
        "encoding/pem"
        "errors"
        "fmt"
@@ -127,6 +128,7 @@ func decodeEKBlock(b *pem.Block, ek *attest.EK) error {
                        return fmt.Errorf("error parsing EKCert: %v", err)
                }
                ek.Certificate = cert
+               ek.Certificate.UnhandledCriticalExtensions = []asn1.ObjectIdentifier{}
                return nil

        case "PUBLIC KEY":
```
but a more tactful approach is probably needed. Maybe have a list of known extensions that can be ignored? Alternatively there are some more lower level ways to verify a certificate is signed by a CA, but that also removes a bunch of other checks we might want to keep.

This can be worked around by using hashes, but that's not ideal.

### PR DESCRIPTION
**Pull request by arianvp**
Fixes #19

### CODE REVIEW

**Comment by arianvp** [comment]
@kfox1111 care to have a look? Without this golang fails to validate spec-compliant EKCerts

File: pkg/server/server.go [hunk 1]
```diff
@@ -177,8 +181,37 @@ func (p *Plugin) Attest(stream nodeattestorv1.NodeAttestor_AttestServer) error {
...
+					return status.Errorf(codes.InvalidArgument, "tpm: could not parse SANs of EKCertt : %v", err)
+				}
+			}
+		}
+
+		oidTcgKpEKCertificate := asn1.ObjectIdentifier{2, 23, 133, 8, 1}
+		for _, id := range ek.Certificate.UnknownExtKeyUsage {
+			if id.Equal(oidTcgKpEKCertificate) {
+			}
+		}
```
Comment (kfox1111) [inline pkg/server/server.go]: Dead code?

File: pkg/server/server.go [hunk 2]
```diff
@@ -177,8 +181,37 @@ func (p *Plugin) Attest(stream nodeattestorv1.NodeAttestor_AttestServer) error {
...
 		opts := x509.VerifyOptions{
 			Roots: roots,
+			// EKCert contains an unknown ExtKeyUsage tcg-kp-EKCertificate
+			// 2.23.133.8.1 which go doesn't support, so we need to disable
+			// key-usage checking. even if it was supported, Go wants to have
+			// the same key usages down the whole chain but already found
+			// one manufacturer in the wild that doesn't follow the advise in
+			// the spec and doesn't set the key usage extension on their root
+			// certificates.
+			KeyUsages: []x509.ExtKeyUsage{x509.ExtKeyUsageAny},
```
Comment (kfox1111) [inline pkg/server/server.go:192]: Is usage any too open? Is there a more limited form we could use?

**Review by kfox1111 — COMMENTED** [review]
Thanks for working on this. Sorry for the delay. Some questions inline

File: pkg/server/server.go (hunk 2 above)
Comment (arianvp) [reply pkg/server/server.go:192]: Unfortunately it's the only way. This is because Golang enforces key-usage to be consistent across the entire certificate chain but e.g.  Infineon doesn't have key usages set on their root ca.

File: pkg/server/server.go (hunk 1 above)
Comment (arianvp) [reply pkg/server/server.go]: oh no I think we should throw an error here if it's *not* this key usage. Let me add that.

**Comment by arianvp** [comment]
Hmm any idea why CI is not triggering on my PR?

**Comment by kfox1111** [comment]
> Hmm any idea why CI is not triggering on my PR?

hmm... offhand, no. It looks to me like it should work... will try and dig in soon.

**Comment by torfjor** [comment]
Friendly bump 👋. Would be nice to have this upstream!

**Comment by kfox1111** [comment]
Thanks for the reminder. will have a look

**Comment by kfox1111** [comment]
Looks like the only thing outstanding is a fix for the deadcode/exception handling.

**Comment by arianvp** [comment]
I'll fix this tomorrow.

File: pkg/server/server.go (hunk 1 above)
Comment (arianvp) [reply pkg/server/server.go]: To solve this correctly in a way that is forwards and backwards compatible we need https://github.com/golang/go/issues/75325

Otherwise, if golang ever starts accepting this OID in the standard library, this code will break.

Luckily this just landed in Go  1.26

How aggressive is SPIRE with adopting new go versions? If we are fine with requiring  Go 1.26,I can make the check. Otherwise I  suggest we  remove this code completely and file an issue to improve this  later

Comment (arianvp) [reply pkg/server/server.go]: go 1.26 lands in February btw

Comment (arianvp) [reply pkg/server/server.go]: after further reading the spec; the field is not critical and also not mandatory. it's marked as `Extended Key Usage ExtKeyUsageSyntax tcg-kp-EKCertificate MAY
non-critical`

So I think I'm going to leave it out for now.  As there might be EK Certs in the wild that do not have the field.

https://trustedcomputinggroup.org/wp-content/uploads/TCG-EK-Credential-Profile-for-TPM-Family-2.0-Level-0-Version-2.6_pub.pdf

Comment (arianvp) [reply pkg/server/server.go]: Oh look at this: Merged a few days ago: https://github.com/google/go-attestation/pull/471 🥳

File: go.mod [hunk 3]
```diff
@@ -1,38 +1,44 @@
...
 
-go 1.23.0
-
-toolchain go1.23.2
+go 1.24.0
 
 require (
-	github.com/google/go-attestation v0.4.4-0.20220404204839-8820d49b18d9
-	github.com/google/go-tpm-tools v0.3.8
+	github.com/google/go-attestation v0.6.1-0.20260123045045-5514d09200e7
```
Comment (arianvp) [inline go.mod:6]: This is the (unreleased) commit that implements exactly what we want.  https://github.com/google/go-attestation/commit/5514d09200e7ca5768e8cc09d4fe56ec77df8c4d

**Review by kfox1111 — APPROVED** [review]
LGTM. Thanks! :)

**Comment by kfox1111** [comment]
Some testing failures

**Comment by arianvp** [comment]
I've been trying to get the test suite working locally but it seems incompatible with openssl 3 and my distro doesn't ship anything else...

**Comment by arianvp** [comment]
Okay I'll try to get this fixed. :)

**Comment by arianvp** [comment]
Ah seems CI is running in ubuntu 20.04 which is not even supported anymore. Seems there is quite a bit of work to clean this up. I doubt the test suite even passes on master on newer versions at the moment

**Comment by kfox1111** [comment]
quite possible. The tests were inherited from ages ago.

**Comment by arianvp** [comment]
I commited fixes and ran the tests locally on NixOS and they pass. I naively bumped the CI dockerfile to 24.04 in the hope that that fixes it in CI too

File: ci/docker/Dockerfile [hunk 4]
```diff
@@ -1,6 +1,6 @@
 FROM golang:latest AS go
 
-FROM ubuntu:20.04
+FROM ubuntu:24.04
 
 RUN addgroup --gid 1000 docker \
     && adduser --uid 1000 --ingroup docker --home /home/docker --shell /bin/sh --disabled-password --gecos "" docker
```
Comment (wagdav) [inline ci/docker/Dockerfile]: I suggest to use a different uid and gid for the newly added user because In ubuntu 24.04 the ubuntu user has 1000:1000

File: ci/docker/Dockerfile
Comment (wagdav) [inline ci/docker/Dockerfile:14]: I suggest to include the`adduser`package in the list and move the entire block before `RUN addgroup ...` so that you can use the addgroup and adduser programs .

**Review by wagdav — COMMENTED** [review]
I looked into the build errors and I left some suggestions to fix it. Hope it helps to get this merged!

**Comment by arianvp** [comment]
The whole ci seems to be a mess frankly. Giving another shot to clean it up with your suggestions but I have very little tolerance having to deal with docker so if it doesn't work I'll offer switching to Nix for CI or someone else will have to push this PR over the finish line. I'm fine with just pointing my stuff to this branch. The code is working fine for me and all the tests pass :shrug:

**Comment by arianvp** [comment]
I installed podman and podman-compose now but I just get permission denied errors etc. I give up. Someone else can try and fix this. 

Though offer to dump all this docker-compose stuff for doing this with nix still stands :)

**Comment by wagdav** [comment]
@arianvp Using Docker Desktop on Mac, I could build the CI image with your latest changes.  The GitHub Actions is now waiting for a maintainer's approval to run.
 
🤞 🍀

**Comment by kfox1111** [comment]
I was never involved in the tests, so I'm shooting a little blind there, but it looks ok to me.

**Review by kfox1111 — APPROVED** [review]
LGTM. Thanks! :)

**Comment by arianvp** [comment]
Wooohooo!
